### ISSUE TITLE
Can't find the Contributing.md file

### ISSUE THREAD

**Issue by noahweasley** [sddevelopment-be/modular-validators#6]
I checked both branches that exists on the repo, but couldn't find it.

On the readme, clicking on the link to it, gives a 404 error

**Comment by stijn-dejongh** [comment]
It is in the `docs` folder. On the deployed site, the links works well but on the github main page it does not.
I will see if this can be adressed easily.

**Comment by stijn-dejongh** [comment]
I tried adding symlinks to the '.github' directory, similar to how it was done to get the original `README.md` file to be stored in a different directory. Unfortunately, the default display of github does not follow the links, and you end up looking at a file telling you where the source is located.

I guess the only way to resolve this properly is to move the README back to the repository root, but that would make the deployment of the documentation site somewhat troublesome.
